---
title: "A standard format for weather data"
date: "2026-01-29"
---

Data from weather stations are widely used in environmental science.
These are referred to in meteorology as surface observations (as opposed to
atmospheric data or model outputs).
Weather stations typically consist of sensors for air temperature, humidity, wind
speed and direction, radiation in various wavelengths, rainfall, and often
include soil properties - soil temperature, moisture content, water table height
etc.
We often want to bring data together from different sources, apply some quality
control (at least check for outliers), fill in gaps in the time series, and
analyse trends over time.
However, how this process is handled is left to the vagaries of individual
scientists: there is no easily available system for standardisation, or support
for QA/QC, gap filling, visualisation, or re-use.

The most basic problem is simply of agreeing on standard names for variables.
Several conventions exist, but none are widelu used outside the modelling
community. Some naming conventions are listed below.

| Name | Defines | Link | Issues |
|---|---|---|---|
| Climate Forecast (CF) | Names & netCDF file format | [link](https://cfconventions.org/Data/cf-standard-names/docs/guidelines.html), and [from CEDA](https://help.ceda.ac.uk/article/4507-the-cf-metadata-convention) |
| ICOS | Variable names | [link](https://cfconventions.org/Data/cf-standard-names/docs/guidelines.html) | |
| AmeriFlux BADM | Variable names | [link](/ameriflux.lbl.gov/data/badm/badm-standards/) | Does not including most met variables |
| Copernicus Station Exchange Format (SEF) | Variable names | [link](https://datarescue.climate.copernicus.eu/variablenames) | |
| Copernicus Station Exchange Format (SEF) | Plain text file format  | [link](https://datarescue.climate.copernicus.eu/station-exchange-format-sef) | Only one variable per file limits use |
| CEDA BADC-CSV | Plain text file format  | [link](https://help.ceda.ac.uk/article/105-badc-csv) | Format not easily machine-readable |



Nor are these conventions systematically constructed, so are not
easily extended or modified to be more generally usaable.
For example, the Climate Forecast (CF) convention constructs a set of [standard
names](https://cfconventions.org/Data/cf-standard-names/docs/guidelines.html)
used widely in climate modelling. Users are able to suggest new variables names
in an ad hoc manner. The result is there are ~5250 arbitrarily defined variable
names, with no system to their naming.
Only 11 chemical species are defined, themselves arbitrary, so no other chemical species can be referred to without inventing new names.
Currently all the information is in one self-contained string.
